#!/usr/bin/env bash
# agentic.sh — Agentic Protocol CLI for Web UI/UX 设计.
# Auto-generated by cli_writer.py. Source: synthesis.md Section 9.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=../lib/common.sh
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="Web UI/UX 设计"
DIM_COUNT=7

usage() {
  cat <<EOF
agentic.sh — Agentic Protocol CLI for ${INDUSTRY}

拿到 ${INDUSTRY} 行业的新问题时，按 ${DIM_COUNT} 个研究维度做功课再答。
不直接给答案，而是引导你用资深从业者的研究维度收集信息。

USAGE:
  ./agentic.sh                # interactive walkthrough
  ./agentic.sh --dry-run      # walk through but skip file write
  ./agentic.sh --json         # emit JSON to stdout
  ./agentic.sh --explain      # show backing mental models + sources
  ./agentic.sh --help         # this message
EOF
}

explain() {
  cat <<'EOT'
这个 Agentic Protocol 把这一行人面对新问题的研究维度结构化。

研究维度 (7 个):
  9.1 用户目标 + JTBD
  9.2 同类 reference + pattern 扫描
  9.3 数据密度与 IA 判断
  9.4 响应式与设备
  9.5 设计系统选型 + token 边界
  9.6 a11y baseline + 合规要求
  9.7 AI 探索预算 + 决策证据链

来源: synthesis.md Section 9 + Section 1.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a DIM_TITLES=(
  "用户目标 + JTBD"
  "同类 reference + pattern 扫描"
  "数据密度与 IA 判断"
  "响应式与设备"
  "设计系统选型 + token 边界"
  "a11y baseline + 合规要求"
  "AI 探索预算 + 决策证据链"
)
declare -a DIM_QUESTIONS=(
  "为什么用户来这里、解决什么 job、当前怎么解决"
  "别人怎么做这个"
  "主屏要承载多少 metric、何频率刷新、要 drill-down 吗、内容树多深"
  "主要用户在桌面/平板/手机、多窗口吗、touch 还是 hover"
  "公司有没有 DS、选 shadcn/MUI/Carbon/Ant Design/自建、token 三层是否齐备"
  "目标用户 / 地域有合规要求吗（EAA / ADA / GB/T 37668 / DSA）；WCAG AA 各条是否覆盖"
  "能不能用 v0 / Figma Make 撒 20 个方向再选；这个设计的关键决定要 PM / 工程 / 用户研究中的哪个证据来支撑"
)
declare -a DIM_SOURCES=(
  "跑 5 人用户访谈（Nielsen 1993 法则）"
  "Mobbin / Page Flows 找 5-10 个同类 flow"
  "Card sorting / tree testing 决定层级"
  "看 analytics 设备分布"
  "Audit 现有产品 21 种蓝色 14 种间距"
  "跑 axe DevTools + Lighthouse"
  "v0 / Figma Make 30 分钟跑 10-20 个方向→筛 3 个→人工深化"
)
declare -a DIM_OUTPUT_FORMATS=(
  "用 JTBD 句式\"When [situation], I want to [motivation], so I can [outcome]\"；查现有 Hotjar / FullStory 录屏 30 分钟"
  "Refero / Calltoidea 查组件级别参考；记录 3 个最像 + 3 个最不一样的"
  "眯眼测试 hierarchy；F-Pattern vs Z-Pattern 评估扫读路径"
  "Polypane 多视口同步设计；touch target ≥ 24×24 / Apple HIG 44pt / Material 48dp 选档"
  "查 W3C Design Tokens spec 兼容性；评估 shadcn registry / Tokens Studio 接入成本"
  "纯键盘走一遍；screen reader 抽查；查 WCAG 2.2 understanding 文档对应条款"
  "写 hypothesis 卡片\"我们认为 [改动] 会让 [用户] 在 [场景] 达到 [结果]，以 [metric] 验证\"；建决策日志（哪怕 5 行）"
)
declare -a DIM_FINDINGS=()

if [[ $JSON -eq 0 ]]; then
  ms_section "${INDUSTRY} · Agentic Protocol"
  ms_info "拿到的问题是什么? (输入完后，敲一个空行结束)"
  echo
fi

PROBLEM="$(ms_read_multiline)"
ms_buffer_append "# ${INDUSTRY} — Agentic Protocol Report"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## 问题"
ms_buffer_append ""
ms_buffer_append "$PROBLEM"
ms_buffer_append ""

for i in "${!DIM_TITLES[@]}"; do
  if [[ $JSON -eq 0 ]]; then
    ms_section "${DIM_TITLES[$i]}"
    echo "看什么:    ${DIM_QUESTIONS[$i]}"
    echo "在哪看:    ${DIM_SOURCES[$i]}"
    echo "输出格式:  ${DIM_OUTPUT_FORMATS[$i]}"
    echo
    ms_prompt "你的发现 / 推断 (空行结束):"
    echo
  fi
  finding="$(ms_read_multiline)"
  DIM_FINDINGS+=("$finding")

  ms_buffer_append "## ${DIM_TITLES[$i]}"
  ms_buffer_append ""
  ms_buffer_append "**看什么**: ${DIM_QUESTIONS[$i]}"
  ms_buffer_append ""
  ms_buffer_append "**在哪看**: ${DIM_SOURCES[$i]}"
  ms_buffer_append ""
  ms_buffer_append "**发现**:"
  ms_buffer_append ""
  ms_buffer_append "$finding"
  ms_buffer_append ""
done

if [[ $JSON -eq 1 ]]; then
  args=("problem" "$PROBLEM")
  for i in "${!DIM_TITLES[@]}"; do
    args+=("dim_${i}_title" "${DIM_TITLES[$i]}")
    args+=("dim_${i}_finding" "${DIM_FINDINGS[$i]}")
  done
  ms_emit_json "${args[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "agentic-protocol"
fi
